# render.yaml
services:
  - type: web
    name: cts-backend
    runtime: docker
    repo: https://github.com/Darkobs667/cts-backend
    branch: rollback-backend-hier-12h
    plan: free
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_FOLDER
        value: cts/candidates
      - key: CANDIDATE_PHOTO_STORAGE
        value: cloudinary
      - key: CACHE_STORE
        value: database
      - key: CACHE_LIMITER
        value: database
    numInstances: 1
